#:kivy 2.1.0
<ForgotPasswordPage>:
    orientation: 'horizontal'
    padding: dp(10)
    spacing: dp(10)
    size_hint: None, None
    size: dp(300), dp(650)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    BoxLayout:
        orientation: 'vertical'
        padding: dp(5)
        spacing: dp(5)
        size_hint_y: None
        height: dp(600)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        canvas.before:
            Color:
                rgba: 1, 0.984, 0.675, 1
            Rectangle:
                size: self.size
                pos: self.pos
        
        # Header        
        BoxLayout:
            orientation: 'horizontal'
            padding: dp(10)
            spacing: dp(5)
            size_hint_y: None
            height: dp(100)
            canvas.before:
                Color:
                    rgba: 1, 0.984, 0.675, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            Image:
                source: 'assets/logo/Nagcarlan.png'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                height: dp(80)

            BoxLayout:
                orientation: 'vertical'
                spacing: dp(2)
                canvas.before:
                    Color:
                        rgba: 1, 0.984, 0.675, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos

                Label:
                    text: "[color=000000ff][b]SIKLAB - MDRRMO[/b][/color]"
                    markup: True
                    font_name: 'Medium'
                    font_size: dp(12)
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    text: "[color=000000ff]Municipality of Nagcarlan, Laguna[/color]"
                    markup: True
                    font_name: 'Medium'
                    font_size: dp(10)
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size

            Image:
                source: 'assets/logo/mdrrmo.png'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                height: dp(80)
        
        # Body
        BoxLayout:
            orientation: 'vertical'
            padding: dp(10)
            spacing: dp(10)
            size_hint_y: None
            height: dp(400)
            canvas.before:
                Color:
                    rgba: 1, 0.984, 0.675, 1
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [dp(30)]

            Label:
                text: '[color=000000ff][b]VERIFY ACCOUNT[/b][/color]'
                font_name: 'Montserrat'
                font_size: dp(20)
                markup: True
                halign: 'center'
                valign: 'bottom'
                size_hint_y: None
                height: dp(30)

            BoxLayout:
                orientation: 'vertical'
                padding: dp(10)
                spacing: dp(5)
                height: dp(240)
                size_hint: 1, None
                canvas.before:
                    Color:
                        rgba: 1, 0.957, 0.129, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [dp(30)]

                Label:
                    text: "[color=000000ff]Phone Number[/color]"
                    font_name: 'Montserrat'
                    markup: True
                    size_hint: None, None
                    height: dp(30)
                    pos_hint: {'center_x': 0.3}

                TextInput:
                    multiline: False
                    size_hint: None, None
                    size: dp(210), dp(30)
                    pos_hint: {"center_x": 0.5}

                Label:
                    text: "[color=000000ff]Enter OTP[/color]"
                    font_name: 'Montserrat'
                    markup: True
                    size_hint: None, None
                    height: dp(30)
                    pos_hint: {'center_x': 0.2}

                TextInput:
                    multiline: False
                    size_hint: None, None
                    size: dp(210), dp(30)
                    pos_hint: {"center_x": 0.5}

                Button:
                    text: "[color=000000ff]Send OTP[/color]"
                    background_normal: ''  # Remove default background
                    background_down: ''
                    background_color: 0, 0, 0, 0
                    markup: True
                    font_name: 'Montserrat'
                    font_size: dp(13)
                    size_hint: None, None
                    size: dp(100), dp(25)
                    pos_hint: {"center_x": 0.7}
                    on_press: root.sendotp()
                    canvas.before:
                        Color:
                            rgba: (0.1, 0.59, 0, 1)  # Green border color (#199700)
                        Line:
                            width: 1  # Border thickness
                            rounded_rectangle: [self.x, self.y, self.width, self.height, 15]

                Button:
                    text: "Submit"
                    background_normal: ''  # Remove default background
                    background_down: ''
                    background_color: 0, 0, 0, 0  # Make the default button transparent
                    font_name: 'Montserrat'
                    font_size: dp(13)
                    size_hint: None, None
                    pos_hint: {'center_x': 0.5}
                    height: dp(30)
                    width: dp(100)
                    on_press: root.submit()

                    canvas.before:
                        Color:
                            rgba: (0.1, 0.59, 0, 1)  # Green #199700
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]  # Rounded corners (adjust for more/less curve)

            BoxLayout:
                orientation: 'vertical'
                padding: dp(10)
                spacing: dp(5)
                height: dp(110)
                size_hint: 1, None
                pos_hint: {'center_y': 0.5, 'center_x': 0.5}
        #Footer
        BoxLayout:
            orientation: 'vertical'
            padding: dp(10)
            spacing: dp(15)
            size_hint_y: None
            size: dp(150), dp(80)
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint: None, None
                size: dp(100), dp(15)
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

                Image:
                    source: 'assets/logo/contact.png'
                    allow_stretch: True
                    keep_ratio: True
                    size_hint: None, None
                    size: dp(15), dp(15)
                    halign: 'center'
                    valign: 'middle'

                Label:
                    id: hotline_contact
                    text: '[color=000000ff][b]09123456789[/b][/color]'
                    font_name: 'Regular'
                    font_size: dp(10)
                    markup: True
                    size_hint: None, None
                    size: dp(150), dp(15)
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint: None, None
                size: dp(160), dp(15)
                pos_hint: {'center_x': 0.5}

                Image:
                    source: 'assets/logo/email.png'
                    allow_stretch: True
                    keep_ratio: True
                    size_hint: None, None
                    size: dp(15), dp(15)
                    halign: 'center'
                    valign: 'middle'

                Label:
                    id: hotline_email
                    text: '[color=000000ff][b]siklabmdrrmo@gmail.com[/b][/color]'
                    font_name: 'Regular'
                    font_size: dp(10)
                    markup: True
                    size_hint: None, None
                    size: dp(150), dp(15)
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size
