#:kivy 2.1.0
<Typhoon>:
    orientation: 'horizontal'
    padding: dp(10)
    spacing: dp(10)
    size_hint: None, None
    size: dp(300), dp(650)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    BoxLayout:
        orientation: 'vertical'
        padding: dp(5)
        spacing: dp(5)
        size_hint_y: None
        height: dp(600)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        canvas.before:
            Color:
                rgba: 1, 0.984, 0.675, 1
            Rectangle:
                size: self.size
                pos: self.pos
        
        # Header        
        BoxLayout:
            orientation: 'horizontal'
            padding: dp(10)
            spacing: dp(5)
            size_hint_y: None
            height: dp(100)
            canvas.before:
                Color:
                    rgba: 1, 0.984, 0.675, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            Image:
                source: 'assets/logo/Nagcarlan.png'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                height: dp(80)

            BoxLayout:
                orientation: 'vertical'
                spacing: dp(2)
                canvas.before:
                    Color:
                        rgba: 1, 0.984, 0.675, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos

                Label:
                    text: "[color=000000ff][b]SIKLAB - MDRRMO[/b][/color]"
                    font_name: 'Medium'
                    markup: True
                    font_size: dp(12)
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    text: "[color=000000ff]Municipality of Nagcarlan, Laguna[/color]"
                    font_name: 'Medium'
                    markup: True
                    font_size: dp(10)
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size

            Image:
                source: 'assets/logo/mdrrmo.png'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                height: dp(80)
        
        # Body
        BoxLayout:
            orientation: 'vertical'
            padding: dp(10)
            spacing: dp(10)
            size_hint: 1, None
            height: dp(430)
            canvas.before:
                Color:
                    rgba: 1, 0.984, 0.675, 1
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [dp(15)]

            BoxLayout:
                orientation: 'vertical'
                padding: dp(10)
                spacing: dp(10)
                size_hint: 1, None
                height: dp(50)

                FloatLayout:
                    Button:
                        background_normal: ''  
                        background_down: ''
                        background_color: 0, 0, 0, 0  
                        size_hint: None, None
                        pos_hint: {'center_x': 0.05, 'center_y': 0.5}
                        height: dp(40)
                        width: dp(40)
                        on_press: root.back()
                    Image:
                        source: 'assets/logo/back.png'  # Your icon path
                        size_hint: None, None
                        size: dp(20), dp(20)
                        pos_hint: {'center_x': 0.1, 'center_y': 0.5}

                Label:
                    text: '[color=000000ff][b]TYPHOON[/b][/color]'
                    font_name: 'Medium'
                    markup: True
                    font_size: dp(25)
                    size_hint: None, None
                    pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            BoxLayout:
                orientation: 'vertical'
                padding: dp(10)
                spacing: dp(10)
                size_hint_y: None
                height: dp(200)

                Label:
                    text: '[color=000000ff]EMERGENCY KIT:[/color]'
                    font_name: 'Medium'
                    markup: True
                    font_size: dp(18)
                    halign: 'center'
                    valgin: 'middle'             
                    height: dp(20)
                Label:
                    text: '[color=000000ff]Flashlight and Extra Batteries[/color]'
                    font_name: 'Regular'
                    markup: True
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)
                Label:
                    text: '[color=000000ff]First Aid Kit and Manual[/color]'
                    markup: True
                    font_name: 'Regular'
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)
                Label:
                    text: '[color=000000ff]Emergency Food and Water[/color]'
                    markup: True
                    font_name: 'Regular'
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)
                Label:
                    text: '[color=000000ff]Essential Medicine[/color]'
                    markup: True
                    font_name: 'Regular'
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)
                Label:
                    text: '[color=000000ff]Facemask[/color]'
                    markup: True
                    font_name: 'Regular'
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)
                Label:
                    text: '[color=000000ff]Goggles[/color]'
                    markup: True
                    font_name: 'Regular'
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)
                Label:
                    text: '[color=000000ff]Battery-Powered Radio[/color]'
                    markup: True
                    font_name: 'Regular'
                    font_size: dp(15)
                    halign: 'left'
                    valgin: 'middle'             
                    height: dp(15)

            BoxLayout:
                orientation: 'vertical'
                padding: dp(10)
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        BoxLayout:
            orientation: 'vertical'
            padding: dp(10)
            spacing: dp(10)
            size_hint_y: None
            height: dp(50)
            canvas.before:
                Color:
                    rgba: 1, 0.957, 0.129, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                
            Button:
                text: '[color=000000ff][b]EMERGENCY[/b][/color]'
                markup: True
                font_size: dp(20)
                font_name: 'Medium'
                background_normal: ''
                background_down: ''
                background_color: 1, 0.957, 0.129, 1
                halign: 'center'
                valign: 'bottom'
                size: dp(350), dp(55)
                on_press: root.emergency()
                